// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_logs.sql

package db

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const writeAuditLog = `-- name: WriteAuditLog :exec
INSERT INTO audit_logs (
  actor_id,
  actor_role,
  action,
  resource_type,
  resource_id,
  ip_address,
  user_agent,
  meta_data
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type WriteAuditLogParams struct {
	ActorID      pgtype.Int8
	ActorRole    NullUserRole
	Action       string
	ResourceType string
	ResourceID   pgtype.Int8
	IpAddress    *netip.Addr
	UserAgent    pgtype.Text
	MetaData     []byte
}

func (q *Queries) WriteAuditLog(ctx context.Context, arg WriteAuditLogParams) error {
	_, err := q.db.Exec(ctx, writeAuditLog,
		arg.ActorID,
		arg.ActorRole,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.IpAddress,
		arg.UserAgent,
		arg.MetaData,
	)
	return err
}
