// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: auth_credentials.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPasswordCredential = `-- name: CreatePasswordCredential :one
INSERT INTO auth_credentials (user_id, provider, password_hash)
VALUES ($1, 'password', $2)
RETURNING id, user_id, provider, provider_user_id, password_hash, last_login_at, created_at, updated_at, deleted_at
`

type CreatePasswordCredentialParams struct {
	UserID       int64       `json:"user_id"`
	PasswordHash pgtype.Text `json:"password_hash"`
}

func (q *Queries) CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) (AuthCredential, error) {
	row := q.db.QueryRow(ctx, createPasswordCredential, arg.UserID, arg.PasswordHash)
	var i AuthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPasswordCredentialByUserID = `-- name: GetPasswordCredentialByUserID :one
SELECT id, user_id, provider, provider_user_id, password_hash, last_login_at, created_at, updated_at, deleted_at FROM auth_credentials
WHERE user_id = $1
  AND provider = 'password'
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPasswordCredentialByUserID(ctx context.Context, userID int64) (AuthCredential, error) {
	row := q.db.QueryRow(ctx, getPasswordCredentialByUserID, userID)
	var i AuthCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.PasswordHash,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateAuthCredentialLastLogin = `-- name: UpdateAuthCredentialLastLogin :exec
UPDATE auth_credentials
SET last_login_at = NOW(),
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAuthCredentialLastLogin(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateAuthCredentialLastLogin, id)
	return err
}
