// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: carts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearCart = `-- name: ClearCart :exec
UPDATE cart_items SET deleted_at = NOW() WHERE cart_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ClearCart(ctx context.Context, cartID int64) error {
	_, err := q.db.Exec(ctx, clearCart, cartID)
	return err
}

const createCart = `-- name: CreateCart :one
INSERT INTO carts (user_id, restaurant_id) VALUES ($1, $2) RETURNING id, user_id, restaurant_id, created_at, updated_at, deleted_at
`

type CreateCartParams struct {
	UserID       int64       `json:"user_id"`
	RestaurantID pgtype.Int8 `json:"restaurant_id"`
}

func (q *Queries) CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error) {
	row := q.db.QueryRow(ctx, createCart, arg.UserID, arg.RestaurantID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteCart = `-- name: DeleteCart :exec
UPDATE carts SET deleted_at = NOW(), updated_at = NOW() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteCart(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteCart, id)
	return err
}

const getCartByUser = `-- name: GetCartByUser :one
SELECT id, user_id, restaurant_id, created_at, updated_at, deleted_at FROM carts WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCartByUser(ctx context.Context, userID int64) (Cart, error) {
	row := q.db.QueryRow(ctx, getCartByUser, userID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCartItems = `-- name: ListCartItems :many
SELECT ci.id, ci.cart_id, ci.menu_item_id, ci.quantity, ci.note, ci.created_at, ci.updated_at,
       mi.name AS menu_item_name, mi.price_amount AS menu_item_price, mi.image_url AS menu_item_image
FROM cart_items ci
JOIN menu_items mi ON ci.menu_item_id = mi.id
WHERE ci.cart_id = $1 AND ci.deleted_at IS NULL
ORDER BY ci.created_at ASC
`

type ListCartItemsRow struct {
	ID            int64              `json:"id"`
	CartID        int64              `json:"cart_id"`
	MenuItemID    int64              `json:"menu_item_id"`
	Quantity      int32              `json:"quantity"`
	Note          pgtype.Text        `json:"note"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	MenuItemName  string             `json:"menu_item_name"`
	MenuItemPrice int64              `json:"menu_item_price"`
	MenuItemImage pgtype.Text        `json:"menu_item_image"`
}

func (q *Queries) ListCartItems(ctx context.Context, cartID int64) ([]ListCartItemsRow, error) {
	rows, err := q.db.Query(ctx, listCartItems, cartID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCartItemsRow
	for rows.Next() {
		var i ListCartItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.CartID,
			&i.MenuItemID,
			&i.Quantity,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.MenuItemName,
			&i.MenuItemPrice,
			&i.MenuItemImage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeCartItem = `-- name: RemoveCartItem :exec
UPDATE cart_items SET deleted_at = NOW() WHERE cart_id = $1 AND menu_item_id = $2 AND deleted_at IS NULL
`

type RemoveCartItemParams struct {
	CartID     int64 `json:"cart_id"`
	MenuItemID int64 `json:"menu_item_id"`
}

func (q *Queries) RemoveCartItem(ctx context.Context, arg RemoveCartItemParams) error {
	_, err := q.db.Exec(ctx, removeCartItem, arg.CartID, arg.MenuItemID)
	return err
}

const updateCartRestaurant = `-- name: UpdateCartRestaurant :one
UPDATE carts SET restaurant_id = $1, updated_at = NOW()
WHERE id = $2 AND deleted_at IS NULL RETURNING id, user_id, restaurant_id, created_at, updated_at, deleted_at
`

type UpdateCartRestaurantParams struct {
	RestaurantID pgtype.Int8 `json:"restaurant_id"`
	ID           int64       `json:"id"`
}

func (q *Queries) UpdateCartRestaurant(ctx context.Context, arg UpdateCartRestaurantParams) (Cart, error) {
	row := q.db.QueryRow(ctx, updateCartRestaurant, arg.RestaurantID, arg.ID)
	var i Cart
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RestaurantID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertCartItem = `-- name: UpsertCartItem :one
INSERT INTO cart_items (cart_id, menu_item_id, quantity, note)
VALUES ($1, $2, $3, $4)
ON CONFLICT (cart_id, menu_item_id) WHERE deleted_at IS NULL
DO UPDATE SET quantity = EXCLUDED.quantity, note = EXCLUDED.note, updated_at = NOW()
RETURNING id, cart_id, menu_item_id, quantity, note, created_at, updated_at, deleted_at
`

type UpsertCartItemParams struct {
	CartID     int64       `json:"cart_id"`
	MenuItemID int64       `json:"menu_item_id"`
	Quantity   int32       `json:"quantity"`
	Note       pgtype.Text `json:"note"`
}

func (q *Queries) UpsertCartItem(ctx context.Context, arg UpsertCartItemParams) (CartItem, error) {
	row := q.db.QueryRow(ctx, upsertCartItem,
		arg.CartID,
		arg.MenuItemID,
		arg.Quantity,
		arg.Note,
	)
	var i CartItem
	err := row.Scan(
		&i.ID,
		&i.CartID,
		&i.MenuItemID,
		&i.Quantity,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
