// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: menu.sql

package db

import (
	"context"
)

const listMenuCategoriesByRestaurant = `-- name: ListMenuCategoriesByRestaurant :many
SELECT id, restaurant_id, name, sort_order, created_at, updated_at, deleted_at FROM menu_categories
WHERE restaurant_id = $1 AND deleted_at IS NULL
ORDER BY sort_order ASC, name ASC
`

func (q *Queries) ListMenuCategoriesByRestaurant(ctx context.Context, restaurantID int64) ([]MenuCategory, error) {
	rows, err := q.db.Query(ctx, listMenuCategoriesByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuCategory
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.Name,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsByRestaurant = `-- name: ListMenuItemsByRestaurant :many
SELECT id, restaurant_id, category_id, name, description, image_url, price_amount, is_available, created_at, updated_at, deleted_at FROM menu_items
WHERE restaurant_id = $1 AND deleted_at IS NULL AND is_available = true
ORDER BY category_id ASC, name ASC
`

func (q *Queries) ListMenuItemsByRestaurant(ctx context.Context, restaurantID int64) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByRestaurant, restaurantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.RestaurantID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.PriceAmount,
			&i.IsAvailable,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
