// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider string

const (
	AuthProviderPassword AuthProvider = "password"
	AuthProviderGoogle   AuthProvider = "google"
	AuthProviderApple    AuthProvider = "apple"
	AuthProviderFacebook AuthProvider = "facebook"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider
	Valid        bool // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type DeliveryStatus string

const (
	DeliveryStatusUnassigned DeliveryStatus = "unassigned"
	DeliveryStatusAssigned   DeliveryStatus = "assigned"
	DeliveryStatusPickedUp   DeliveryStatus = "picked_up"
	DeliveryStatusDelivered  DeliveryStatus = "delivered"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus
	Valid          bool // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type FavoriteTargetType string

const (
	FavoriteTargetTypeRestaurant FavoriteTargetType = "restaurant"
	FavoriteTargetTypeMenuItem   FavoriteTargetType = "menu_item"
)

func (e *FavoriteTargetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FavoriteTargetType(s)
	case string:
		*e = FavoriteTargetType(s)
	default:
		return fmt.Errorf("unsupported scan type for FavoriteTargetType: %T", src)
	}
	return nil
}

type NullFavoriteTargetType struct {
	FavoriteTargetType FavoriteTargetType
	Valid              bool // Valid is true if FavoriteTargetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFavoriteTargetType) Scan(value interface{}) error {
	if value == nil {
		ns.FavoriteTargetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FavoriteTargetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFavoriteTargetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FavoriteTargetType), nil
}

type NotificationChannel string

const (
	NotificationChannelInApp NotificationChannel = "in_app"
	NotificationChannelEmail NotificationChannel = "email"
	NotificationChannelSms   NotificationChannel = "sms"
	NotificationChannelPush  NotificationChannel = "push"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel
	Valid               bool // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

type NotificationType string

const (
	NotificationTypeOrderUpdate    NotificationType = "order_update"
	NotificationTypeDeliveryUpdate NotificationType = "delivery_update"
	NotificationTypePromotion      NotificationType = "promotion"
	NotificationTypeSystem         NotificationType = "system"
	NotificationTypeReviewRequest  NotificationType = "review_request"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType
	Valid            bool // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusConfirmed OrderStatus = "confirmed"
	OrderStatusPreparing OrderStatus = "preparing"
	OrderStatusReady     OrderStatus = "ready"
	OrderStatusPickedUp  OrderStatus = "picked_up"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus
	Valid       bool // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentProvider string

const (
	PaymentProviderStripe    PaymentProvider = "stripe"
	PaymentProviderPaypal    PaymentProvider = "paypal"
	PaymentProviderWechatPay PaymentProvider = "wechat_pay"
	PaymentProviderAlipay    PaymentProvider = "alipay"
	PaymentProviderCash      PaymentProvider = "cash"
)

func (e *PaymentProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProvider(s)
	case string:
		*e = PaymentProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProvider: %T", src)
	}
	return nil
}

type NullPaymentProvider struct {
	PaymentProvider PaymentProvider
	Valid           bool // Valid is true if PaymentProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProvider) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProvider), nil
}

type PaymentStatus string

const (
	PaymentStatusPending           PaymentStatus = "pending"
	PaymentStatusProcessing        PaymentStatus = "processing"
	PaymentStatusSucceeded         PaymentStatus = "succeeded"
	PaymentStatusFailed            PaymentStatus = "failed"
	PaymentStatusCancelled         PaymentStatus = "cancelled"
	PaymentStatusRefunded          PaymentStatus = "refunded"
	PaymentStatusPartiallyRefunded PaymentStatus = "partially_refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus
	Valid         bool // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PayoutStatus string

const (
	PayoutStatusPending    PayoutStatus = "pending"
	PayoutStatusProcessing PayoutStatus = "processing"
	PayoutStatusPaid       PayoutStatus = "paid"
	PayoutStatusFailed     PayoutStatus = "failed"
	PayoutStatusCancelled  PayoutStatus = "cancelled"
)

func (e *PayoutStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutStatus(s)
	case string:
		*e = PayoutStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutStatus: %T", src)
	}
	return nil
}

type NullPayoutStatus struct {
	PayoutStatus PayoutStatus
	Valid        bool // Valid is true if PayoutStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutStatus), nil
}

type PromotionStatus string

const (
	PromotionStatusDraft   PromotionStatus = "draft"
	PromotionStatusActive  PromotionStatus = "active"
	PromotionStatusPaused  PromotionStatus = "paused"
	PromotionStatusExpired PromotionStatus = "expired"
)

func (e *PromotionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromotionStatus(s)
	case string:
		*e = PromotionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PromotionStatus: %T", src)
	}
	return nil
}

type NullPromotionStatus struct {
	PromotionStatus PromotionStatus
	Valid           bool // Valid is true if PromotionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromotionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PromotionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromotionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromotionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromotionStatus), nil
}

type PromotionType string

const (
	PromotionTypePercentOff   PromotionType = "percent_off"
	PromotionTypeAmountOff    PromotionType = "amount_off"
	PromotionTypeFreeDelivery PromotionType = "free_delivery"
	PromotionTypeBogo         PromotionType = "bogo"
)

func (e *PromotionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromotionType(s)
	case string:
		*e = PromotionType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromotionType: %T", src)
	}
	return nil
}

type NullPromotionType struct {
	PromotionType PromotionType
	Valid         bool // Valid is true if PromotionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromotionType) Scan(value interface{}) error {
	if value == nil {
		ns.PromotionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromotionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromotionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromotionType), nil
}

type RefundStatus string

const (
	RefundStatusPending    RefundStatus = "pending"
	RefundStatusProcessing RefundStatus = "processing"
	RefundStatusSucceeded  RefundStatus = "succeeded"
	RefundStatusFailed     RefundStatus = "failed"
	RefundStatusCancelled  RefundStatus = "cancelled"
)

func (e *RefundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefundStatus(s)
	case string:
		*e = RefundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RefundStatus: %T", src)
	}
	return nil
}

type NullRefundStatus struct {
	RefundStatus RefundStatus
	Valid        bool // Valid is true if RefundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RefundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefundStatus), nil
}

type ReviewTargetType string

const (
	ReviewTargetTypeRestaurant ReviewTargetType = "restaurant"
	ReviewTargetTypeRider      ReviewTargetType = "rider"
	ReviewTargetTypeMenuItem   ReviewTargetType = "menu_item"
)

func (e *ReviewTargetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewTargetType(s)
	case string:
		*e = ReviewTargetType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewTargetType: %T", src)
	}
	return nil
}

type NullReviewTargetType struct {
	ReviewTargetType ReviewTargetType
	Valid            bool // Valid is true if ReviewTargetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewTargetType) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewTargetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewTargetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewTargetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewTargetType), nil
}

type RiderOnlineStatus string

const (
	RiderOnlineStatusOffline    RiderOnlineStatus = "offline"
	RiderOnlineStatusOnline     RiderOnlineStatus = "online"
	RiderOnlineStatusOnDelivery RiderOnlineStatus = "on_delivery"
)

func (e *RiderOnlineStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiderOnlineStatus(s)
	case string:
		*e = RiderOnlineStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RiderOnlineStatus: %T", src)
	}
	return nil
}

type NullRiderOnlineStatus struct {
	RiderOnlineStatus RiderOnlineStatus
	Valid             bool // Valid is true if RiderOnlineStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiderOnlineStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RiderOnlineStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiderOnlineStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiderOnlineStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiderOnlineStatus), nil
}

type RiderVehicleType string

const (
	RiderVehicleTypeBicycle   RiderVehicleType = "bicycle"
	RiderVehicleTypeEBike     RiderVehicleType = "e_bike"
	RiderVehicleTypeScooter   RiderVehicleType = "scooter"
	RiderVehicleTypeMotorbike RiderVehicleType = "motorbike"
	RiderVehicleTypeCar       RiderVehicleType = "car"
)

func (e *RiderVehicleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiderVehicleType(s)
	case string:
		*e = RiderVehicleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RiderVehicleType: %T", src)
	}
	return nil
}

type NullRiderVehicleType struct {
	RiderVehicleType RiderVehicleType
	Valid            bool // Valid is true if RiderVehicleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiderVehicleType) Scan(value interface{}) error {
	if value == nil {
		ns.RiderVehicleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiderVehicleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiderVehicleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiderVehicleType), nil
}

type UserRole string

const (
	UserRoleCustomer UserRole = "customer"
	UserRoleRider    UserRole = "rider"
	UserRoleAdmin    UserRole = "admin"
	UserRoleMerchant UserRole = "merchant"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WebhookEventStatus string

const (
	WebhookEventStatusReceived   WebhookEventStatus = "received"
	WebhookEventStatusProcessing WebhookEventStatus = "processing"
	WebhookEventStatusSucceeded  WebhookEventStatus = "succeeded"
	WebhookEventStatusFailed     WebhookEventStatus = "failed"
	WebhookEventStatusSkipped    WebhookEventStatus = "skipped"
)

func (e *WebhookEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookEventStatus(s)
	case string:
		*e = WebhookEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookEventStatus: %T", src)
	}
	return nil
}

type NullWebhookEventStatus struct {
	WebhookEventStatus WebhookEventStatus
	Valid              bool // Valid is true if WebhookEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookEventStatus), nil
}

type Address struct {
	ID           int64
	UserID       int64
	Label        pgtype.Text
	AddressLine1 string
	AddressLine2 pgtype.Text
	City         string
	Postcode     string
	Lat          pgtype.Numeric
	Lng          pgtype.Numeric
	IsDefault    bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type AuditLog struct {
	ID           int64
	ActorID      pgtype.Int8
	ActorRole    NullUserRole
	Action       string
	ResourceType string
	ResourceID   pgtype.Int8
	IpAddress    *netip.Addr
	UserAgent    pgtype.Text
	MetaData     []byte
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type AuthCredential struct {
	ID             int64
	UserID         int64
	Provider       AuthProvider
	ProviderUserID pgtype.Text
	PasswordHash   pgtype.Text
	LastLoginAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Cart struct {
	ID           int64
	UserID       int64
	RestaurantID pgtype.Int8
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type CartItem struct {
	ID         int64
	CartID     int64
	MenuItemID int64
	Quantity   int32
	Note       pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type Delivery struct {
	ID          int64
	OrderID     int64
	RiderID     pgtype.Int8
	Status      DeliveryStatus
	PickedUpAt  pgtype.Timestamptz
	DeliveredAt pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type DeliveryLocationEvent struct {
	ID             int64
	DeliveryID     int64
	RiderID        int64
	Lat            pgtype.Numeric
	Lng            pgtype.Numeric
	AccuracyMeters pgtype.Numeric
	HeadingDegrees pgtype.Numeric
	SpeedMps       pgtype.Numeric
	RecordedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Favorite struct {
	ID         int64
	UserID     int64
	TargetType FavoriteTargetType
	TargetID   int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type FeatureFlag struct {
	ID             int64
	Key            string
	Description    pgtype.Text
	IsEnabled      bool
	RolloutPercent int16
	Config         []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type FeatureFlagOverride struct {
	ID            int64
	FeatureFlagID int64
	UserID        int64
	IsEnabled     bool
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	DeletedAt     pgtype.Timestamptz
}

type MenuCategory struct {
	ID           int64
	RestaurantID int64
	Name         string
	SortOrder    int32
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type MenuItem struct {
	ID           int64
	RestaurantID int64
	CategoryID   pgtype.Int8
	Name         string
	Description  pgtype.Text
	ImageUrl     pgtype.Text
	PriceAmount  int64
	IsAvailable  bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type MenuItemOption struct {
	ID         int64
	MenuItemID int64
	Name       string
	IsRequired bool
	MinSelect  int32
	MaxSelect  int32
	SortOrder  int32
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type MenuItemOptionValue struct {
	ID          int64
	OptionID    int64
	Name        string
	PriceAmount int64
	SortOrder   int32
	IsDefault   bool
	IsAvailable bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type Notification struct {
	ID        int64
	UserID    int64
	Channel   NotificationChannel
	Type      NotificationType
	Title     string
	Body      string
	MetaData  []byte
	ReadAt    pgtype.Timestamptz
	SentAt    pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Order struct {
	ID                int64
	CustomerID        int64
	RestaurantID      int64
	AddressID         pgtype.Int8
	Status            OrderStatus
	SubtotalAmount    int64
	DeliveryFeeAmount int64
	TotalAmount       int64
	Note              pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type OrderItem struct {
	ID          int64
	OrderID     int64
	MenuItemID  int64
	Name        string
	PriceAmount int64
	Quantity    int32
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type OrderItemOption struct {
	ID              int64
	OrderItemID     int64
	OptionID        pgtype.Int8
	OptionValueID   pgtype.Int8
	OptionName      string
	OptionValueName string
	PriceAmount     int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}

type OrderStatusEvent struct {
	ID          int64
	OrderID     int64
	FromStatus  NullOrderStatus
	ToStatus    OrderStatus
	ChangedByID pgtype.Int8
	Reason      pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type PageSchema struct {
	ID             int64
	Key            string
	CurrentVersion int32
	SchemaData     []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type PageSchemaVersion struct {
	ID           int64
	PageSchemaID int64
	Version      int32
	SchemaData   []byte
	Note         pgtype.Text
	CreatorID    int64
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type Payment struct {
	ID                int64
	OrderID           int64
	UserID            int64
	Provider          PaymentProvider
	ProviderPaymentID pgtype.Text
	Status            PaymentStatus
	Amount            int64
	Currency          string
	FailureReason     pgtype.Text
	PaidAt            pgtype.Timestamptz
	MetaData          []byte
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type PaymentRefund struct {
	ID               int64
	PaymentID        int64
	ProviderRefundID pgtype.Text
	Status           RefundStatus
	Amount           int64
	Reason           pgtype.Text
	RefundedAt       pgtype.Timestamptz
	MetaData         []byte
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type Permission struct {
	ID          int64
	Code        string
	Description pgtype.Text
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type Promotion struct {
	ID                int64
	Code              string
	Name              string
	Description       pgtype.Text
	Type              PromotionType
	Status            PromotionStatus
	PercentOff        pgtype.Int2
	AmountOff         pgtype.Int8
	MinOrderAmount    int64
	MaxDiscountAmount pgtype.Int8
	UsageLimit        pgtype.Int4
	PerUserLimit      pgtype.Int4
	RedemptionCount   int32
	StartsAt          pgtype.Timestamptz
	EndsAt            pgtype.Timestamptz
	RestaurantID      pgtype.Int8
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type PromotionRedemption struct {
	ID             int64
	PromotionID    int64
	UserID         int64
	OrderID        int64
	DiscountAmount int64
	RedeemedAt     pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type Restaurant struct {
	ID           int64
	OwnerID      int64
	Name         string
	Description  pgtype.Text
	ImageUrl     pgtype.Text
	AddressLine1 string
	City         string
	Postcode     string
	Lat          pgtype.Numeric
	Lng          pgtype.Numeric
	Phone        pgtype.Text
	IsOpen       bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type RestaurantOperatingHour struct {
	ID           int64
	RestaurantID int64
	DayOfWeek    int16
	OpenTime     pgtype.Time
	CloseTime    pgtype.Time
	IsClosed     bool
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}

type RestaurantPayout struct {
	ID                int64
	RestaurantID      int64
	PeriodStartDate   pgtype.Date
	PeriodEndDate     pgtype.Date
	GrossAmount       int64
	PlatformFeeAmount int64
	AdjustmentAmount  int64
	NetAmount         int64
	Currency          string
	Status            PayoutStatus
	PaidAt            pgtype.Timestamptz
	Reference         pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type Review struct {
	ID         int64
	OrderID    int64
	AuthorID   int64
	TargetType ReviewTargetType
	TargetID   int64
	Rating     int16
	Comment    pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	DeletedAt  pgtype.Timestamptz
}

type RiderProfile struct {
	ID                  int64
	UserID              int64
	VehicleType         RiderVehicleType
	VehiclePlate        pgtype.Text
	LicenseNumber       pgtype.Text
	LicenseExpiresAt    pgtype.Timestamptz
	IsVerified          bool
	OnlineStatus        RiderOnlineStatus
	CurrentLat          pgtype.Numeric
	CurrentLng          pgtype.Numeric
	LocationUpdatedAt   pgtype.Timestamptz
	RatingAverage       pgtype.Numeric
	RatingCount         int32
	CompletedDeliveries int32
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	DeletedAt           pgtype.Timestamptz
}

type Role struct {
	ID        int64
	Code      string
	Name      string
	Persona   UserRole
	IsSystem  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type RolePermission struct {
	RoleID       int64
	PermissionID int64
	GrantedAt    pgtype.Timestamptz
}

type Session struct {
	ID               int64
	UserID           int64
	RefreshTokenHash string
	UserAgent        pgtype.Text
	IpAddress        *netip.Addr
	DeviceID         pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
	LastUsedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	DeletedAt        pgtype.Timestamptz
}

type User struct {
	ID        int64
	Name      string
	Email     string
	Phone     pgtype.Text
	Role      UserRole
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type UserPermissionGrant struct {
	UserID       int64
	PermissionID int64
	Effect       int16
	Scope        []byte
	Reason       pgtype.Text
	GrantedBy    pgtype.Int8
	GrantedAt    pgtype.Timestamptz
	ExpiresAt    pgtype.Timestamptz
}

type UserRoleAssignment struct {
	UserID    int64
	RoleID    int64
	GrantedBy pgtype.Int8
	GrantedAt pgtype.Timestamptz
	Scope     []byte
	ExpiresAt pgtype.Timestamptz
}

type WebhookEvent struct {
	ID              int64
	Provider        string
	EventType       string
	ProviderEventID string
	Status          WebhookEventStatus
	PayloadData     []byte
	Signature       pgtype.Text
	ErrorMessage    pgtype.Text
	RetryCount      int32
	ProcessedAt     pgtype.Timestamptz
	ReceivedAt      pgtype.Timestamptz
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DeletedAt       pgtype.Timestamptz
}
