// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type AuthProvider string

const (
	AuthProviderPassword AuthProvider = "password"
	AuthProviderGoogle   AuthProvider = "google"
	AuthProviderApple    AuthProvider = "apple"
	AuthProviderFacebook AuthProvider = "facebook"
)

func (e *AuthProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AuthProvider(s)
	case string:
		*e = AuthProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for AuthProvider: %T", src)
	}
	return nil
}

type NullAuthProvider struct {
	AuthProvider AuthProvider `json:"auth_provider"`
	Valid        bool         `json:"valid"` // Valid is true if AuthProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAuthProvider) Scan(value interface{}) error {
	if value == nil {
		ns.AuthProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AuthProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAuthProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AuthProvider), nil
}

type DeliveryStatus string

const (
	DeliveryStatusUnassigned DeliveryStatus = "unassigned"
	DeliveryStatusAssigned   DeliveryStatus = "assigned"
	DeliveryStatusPickedUp   DeliveryStatus = "picked_up"
	DeliveryStatusDelivered  DeliveryStatus = "delivered"
)

func (e *DeliveryStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeliveryStatus(s)
	case string:
		*e = DeliveryStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DeliveryStatus: %T", src)
	}
	return nil
}

type NullDeliveryStatus struct {
	DeliveryStatus DeliveryStatus `json:"delivery_status"`
	Valid          bool           `json:"valid"` // Valid is true if DeliveryStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeliveryStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DeliveryStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeliveryStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeliveryStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeliveryStatus), nil
}

type FavoriteTargetType string

const (
	FavoriteTargetTypeRestaurant FavoriteTargetType = "restaurant"
	FavoriteTargetTypeMenuItem   FavoriteTargetType = "menu_item"
)

func (e *FavoriteTargetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FavoriteTargetType(s)
	case string:
		*e = FavoriteTargetType(s)
	default:
		return fmt.Errorf("unsupported scan type for FavoriteTargetType: %T", src)
	}
	return nil
}

type NullFavoriteTargetType struct {
	FavoriteTargetType FavoriteTargetType `json:"favorite_target_type"`
	Valid              bool               `json:"valid"` // Valid is true if FavoriteTargetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFavoriteTargetType) Scan(value interface{}) error {
	if value == nil {
		ns.FavoriteTargetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FavoriteTargetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFavoriteTargetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FavoriteTargetType), nil
}

type NotificationChannel string

const (
	NotificationChannelInApp NotificationChannel = "in_app"
	NotificationChannelEmail NotificationChannel = "email"
	NotificationChannelSms   NotificationChannel = "sms"
	NotificationChannelPush  NotificationChannel = "push"
)

func (e *NotificationChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationChannel(s)
	case string:
		*e = NotificationChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationChannel: %T", src)
	}
	return nil
}

type NullNotificationChannel struct {
	NotificationChannel NotificationChannel `json:"notification_channel"`
	Valid               bool                `json:"valid"` // Valid is true if NotificationChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationChannel), nil
}

type NotificationType string

const (
	NotificationTypeOrderUpdate    NotificationType = "order_update"
	NotificationTypeDeliveryUpdate NotificationType = "delivery_update"
	NotificationTypePromotion      NotificationType = "promotion"
	NotificationTypeSystem         NotificationType = "system"
	NotificationTypeReviewRequest  NotificationType = "review_request"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type OrderStatus string

const (
	OrderStatusPending   OrderStatus = "pending"
	OrderStatusConfirmed OrderStatus = "confirmed"
	OrderStatusPreparing OrderStatus = "preparing"
	OrderStatusReady     OrderStatus = "ready"
	OrderStatusPickedUp  OrderStatus = "picked_up"
	OrderStatusDelivered OrderStatus = "delivered"
	OrderStatusCancelled OrderStatus = "cancelled"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentProvider string

const (
	PaymentProviderStripe    PaymentProvider = "stripe"
	PaymentProviderPaypal    PaymentProvider = "paypal"
	PaymentProviderWechatPay PaymentProvider = "wechat_pay"
	PaymentProviderAlipay    PaymentProvider = "alipay"
	PaymentProviderCash      PaymentProvider = "cash"
)

func (e *PaymentProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProvider(s)
	case string:
		*e = PaymentProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProvider: %T", src)
	}
	return nil
}

type NullPaymentProvider struct {
	PaymentProvider PaymentProvider `json:"payment_provider"`
	Valid           bool            `json:"valid"` // Valid is true if PaymentProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProvider) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProvider), nil
}

type PaymentStatus string

const (
	PaymentStatusPending           PaymentStatus = "pending"
	PaymentStatusProcessing        PaymentStatus = "processing"
	PaymentStatusSucceeded         PaymentStatus = "succeeded"
	PaymentStatusFailed            PaymentStatus = "failed"
	PaymentStatusCancelled         PaymentStatus = "cancelled"
	PaymentStatusRefunded          PaymentStatus = "refunded"
	PaymentStatusPartiallyRefunded PaymentStatus = "partially_refunded"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PayoutStatus string

const (
	PayoutStatusPending    PayoutStatus = "pending"
	PayoutStatusProcessing PayoutStatus = "processing"
	PayoutStatusPaid       PayoutStatus = "paid"
	PayoutStatusFailed     PayoutStatus = "failed"
	PayoutStatusCancelled  PayoutStatus = "cancelled"
)

func (e *PayoutStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutStatus(s)
	case string:
		*e = PayoutStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutStatus: %T", src)
	}
	return nil
}

type NullPayoutStatus struct {
	PayoutStatus PayoutStatus `json:"payout_status"`
	Valid        bool         `json:"valid"` // Valid is true if PayoutStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutStatus), nil
}

type PromotionStatus string

const (
	PromotionStatusDraft   PromotionStatus = "draft"
	PromotionStatusActive  PromotionStatus = "active"
	PromotionStatusPaused  PromotionStatus = "paused"
	PromotionStatusExpired PromotionStatus = "expired"
)

func (e *PromotionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromotionStatus(s)
	case string:
		*e = PromotionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PromotionStatus: %T", src)
	}
	return nil
}

type NullPromotionStatus struct {
	PromotionStatus PromotionStatus `json:"promotion_status"`
	Valid           bool            `json:"valid"` // Valid is true if PromotionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromotionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PromotionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromotionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromotionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromotionStatus), nil
}

type PromotionType string

const (
	PromotionTypePercentOff   PromotionType = "percent_off"
	PromotionTypeAmountOff    PromotionType = "amount_off"
	PromotionTypeFreeDelivery PromotionType = "free_delivery"
	PromotionTypeBogo         PromotionType = "bogo"
)

func (e *PromotionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PromotionType(s)
	case string:
		*e = PromotionType(s)
	default:
		return fmt.Errorf("unsupported scan type for PromotionType: %T", src)
	}
	return nil
}

type NullPromotionType struct {
	PromotionType PromotionType `json:"promotion_type"`
	Valid         bool          `json:"valid"` // Valid is true if PromotionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPromotionType) Scan(value interface{}) error {
	if value == nil {
		ns.PromotionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PromotionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPromotionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PromotionType), nil
}

type RefundStatus string

const (
	RefundStatusPending    RefundStatus = "pending"
	RefundStatusProcessing RefundStatus = "processing"
	RefundStatusSucceeded  RefundStatus = "succeeded"
	RefundStatusFailed     RefundStatus = "failed"
	RefundStatusCancelled  RefundStatus = "cancelled"
)

func (e *RefundStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RefundStatus(s)
	case string:
		*e = RefundStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RefundStatus: %T", src)
	}
	return nil
}

type NullRefundStatus struct {
	RefundStatus RefundStatus `json:"refund_status"`
	Valid        bool         `json:"valid"` // Valid is true if RefundStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRefundStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RefundStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RefundStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRefundStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RefundStatus), nil
}

type ReviewTargetType string

const (
	ReviewTargetTypeRestaurant ReviewTargetType = "restaurant"
	ReviewTargetTypeRider      ReviewTargetType = "rider"
	ReviewTargetTypeMenuItem   ReviewTargetType = "menu_item"
)

func (e *ReviewTargetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewTargetType(s)
	case string:
		*e = ReviewTargetType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewTargetType: %T", src)
	}
	return nil
}

type NullReviewTargetType struct {
	ReviewTargetType ReviewTargetType `json:"review_target_type"`
	Valid            bool             `json:"valid"` // Valid is true if ReviewTargetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewTargetType) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewTargetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewTargetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewTargetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewTargetType), nil
}

type RiderOnlineStatus string

const (
	RiderOnlineStatusOffline    RiderOnlineStatus = "offline"
	RiderOnlineStatusOnline     RiderOnlineStatus = "online"
	RiderOnlineStatusOnDelivery RiderOnlineStatus = "on_delivery"
)

func (e *RiderOnlineStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiderOnlineStatus(s)
	case string:
		*e = RiderOnlineStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RiderOnlineStatus: %T", src)
	}
	return nil
}

type NullRiderOnlineStatus struct {
	RiderOnlineStatus RiderOnlineStatus `json:"rider_online_status"`
	Valid             bool              `json:"valid"` // Valid is true if RiderOnlineStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiderOnlineStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RiderOnlineStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiderOnlineStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiderOnlineStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiderOnlineStatus), nil
}

type RiderVehicleType string

const (
	RiderVehicleTypeBicycle   RiderVehicleType = "bicycle"
	RiderVehicleTypeEBike     RiderVehicleType = "e_bike"
	RiderVehicleTypeScooter   RiderVehicleType = "scooter"
	RiderVehicleTypeMotorbike RiderVehicleType = "motorbike"
	RiderVehicleTypeCar       RiderVehicleType = "car"
)

func (e *RiderVehicleType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiderVehicleType(s)
	case string:
		*e = RiderVehicleType(s)
	default:
		return fmt.Errorf("unsupported scan type for RiderVehicleType: %T", src)
	}
	return nil
}

type NullRiderVehicleType struct {
	RiderVehicleType RiderVehicleType `json:"rider_vehicle_type"`
	Valid            bool             `json:"valid"` // Valid is true if RiderVehicleType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiderVehicleType) Scan(value interface{}) error {
	if value == nil {
		ns.RiderVehicleType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiderVehicleType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiderVehicleType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiderVehicleType), nil
}

type UserRole string

const (
	UserRoleCustomer UserRole = "customer"
	UserRoleRider    UserRole = "rider"
	UserRoleAdmin    UserRole = "admin"
	UserRoleMerchant UserRole = "merchant"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type WebhookEventStatus string

const (
	WebhookEventStatusReceived   WebhookEventStatus = "received"
	WebhookEventStatusProcessing WebhookEventStatus = "processing"
	WebhookEventStatusSucceeded  WebhookEventStatus = "succeeded"
	WebhookEventStatusFailed     WebhookEventStatus = "failed"
	WebhookEventStatusSkipped    WebhookEventStatus = "skipped"
)

func (e *WebhookEventStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WebhookEventStatus(s)
	case string:
		*e = WebhookEventStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WebhookEventStatus: %T", src)
	}
	return nil
}

type NullWebhookEventStatus struct {
	WebhookEventStatus WebhookEventStatus `json:"webhook_event_status"`
	Valid              bool               `json:"valid"` // Valid is true if WebhookEventStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWebhookEventStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WebhookEventStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WebhookEventStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWebhookEventStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WebhookEventStatus), nil
}

type Address struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	Label        pgtype.Text        `json:"label"`
	AddressLine1 string             `json:"address_line_1"`
	AddressLine2 pgtype.Text        `json:"address_line_2"`
	City         string             `json:"city"`
	Postcode     string             `json:"postcode"`
	Lat          pgtype.Numeric     `json:"lat"`
	Lng          pgtype.Numeric     `json:"lng"`
	IsDefault    bool               `json:"is_default"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type AuditLog struct {
	ID           int64              `json:"id"`
	ActorID      pgtype.Int8        `json:"actor_id"`
	ActorRole    NullUserRole       `json:"actor_role"`
	Action       string             `json:"action"`
	ResourceType string             `json:"resource_type"`
	ResourceID   pgtype.Int8        `json:"resource_id"`
	IpAddress    *netip.Addr        `json:"ip_address"`
	UserAgent    pgtype.Text        `json:"user_agent"`
	MetaData     []byte             `json:"meta_data"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type AuthCredential struct {
	ID             int64              `json:"id"`
	UserID         int64              `json:"user_id"`
	Provider       AuthProvider       `json:"provider"`
	ProviderUserID pgtype.Text        `json:"provider_user_id"`
	PasswordHash   pgtype.Text        `json:"password_hash"`
	LastLoginAt    pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Cart struct {
	ID           int64              `json:"id"`
	UserID       int64              `json:"user_id"`
	RestaurantID pgtype.Int8        `json:"restaurant_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type CartItem struct {
	ID         int64              `json:"id"`
	CartID     int64              `json:"cart_id"`
	MenuItemID int64              `json:"menu_item_id"`
	Quantity   int32              `json:"quantity"`
	Note       pgtype.Text        `json:"note"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Delivery struct {
	ID          int64              `json:"id"`
	OrderID     int64              `json:"order_id"`
	RiderID     pgtype.Int8        `json:"rider_id"`
	Status      DeliveryStatus     `json:"status"`
	PickedUpAt  pgtype.Timestamptz `json:"picked_up_at"`
	DeliveredAt pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type DeliveryLocationEvent struct {
	ID             int64              `json:"id"`
	DeliveryID     int64              `json:"delivery_id"`
	RiderID        int64              `json:"rider_id"`
	Lat            pgtype.Numeric     `json:"lat"`
	Lng            pgtype.Numeric     `json:"lng"`
	AccuracyMeters pgtype.Numeric     `json:"accuracy_meters"`
	HeadingDegrees pgtype.Numeric     `json:"heading_degrees"`
	SpeedMps       pgtype.Numeric     `json:"speed_mps"`
	RecordedAt     pgtype.Timestamptz `json:"recorded_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Favorite struct {
	ID         int64              `json:"id"`
	UserID     int64              `json:"user_id"`
	TargetType FavoriteTargetType `json:"target_type"`
	TargetID   int64              `json:"target_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type FeatureFlag struct {
	ID             int64              `json:"id"`
	Key            string             `json:"key"`
	Description    pgtype.Text        `json:"description"`
	IsEnabled      bool               `json:"is_enabled"`
	RolloutPercent int16              `json:"rollout_percent"`
	Config         []byte             `json:"config"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type FeatureFlagOverride struct {
	ID            int64              `json:"id"`
	FeatureFlagID int64              `json:"feature_flag_id"`
	UserID        int64              `json:"user_id"`
	IsEnabled     bool               `json:"is_enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type MenuCategory struct {
	ID           int64              `json:"id"`
	RestaurantID int64              `json:"restaurant_id"`
	Name         string             `json:"name"`
	SortOrder    int32              `json:"sort_order"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type MenuItem struct {
	ID           int64              `json:"id"`
	RestaurantID int64              `json:"restaurant_id"`
	CategoryID   pgtype.Int8        `json:"category_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	PriceAmount  int64              `json:"price_amount"`
	IsAvailable  bool               `json:"is_available"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type MenuItemOption struct {
	ID         int64              `json:"id"`
	MenuItemID int64              `json:"menu_item_id"`
	Name       string             `json:"name"`
	IsRequired bool               `json:"is_required"`
	MinSelect  int32              `json:"min_select"`
	MaxSelect  int32              `json:"max_select"`
	SortOrder  int32              `json:"sort_order"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type MenuItemOptionValue struct {
	ID          int64              `json:"id"`
	OptionID    int64              `json:"option_id"`
	Name        string             `json:"name"`
	PriceAmount int64              `json:"price_amount"`
	SortOrder   int32              `json:"sort_order"`
	IsDefault   bool               `json:"is_default"`
	IsAvailable bool               `json:"is_available"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Notification struct {
	ID        int64               `json:"id"`
	UserID    int64               `json:"user_id"`
	Channel   NotificationChannel `json:"channel"`
	Type      NotificationType    `json:"type"`
	Title     string              `json:"title"`
	Body      string              `json:"body"`
	MetaData  []byte              `json:"meta_data"`
	ReadAt    pgtype.Timestamptz  `json:"read_at"`
	SentAt    pgtype.Timestamptz  `json:"sent_at"`
	CreatedAt pgtype.Timestamptz  `json:"created_at"`
	UpdatedAt pgtype.Timestamptz  `json:"updated_at"`
	DeletedAt pgtype.Timestamptz  `json:"deleted_at"`
}

type Order struct {
	ID                int64              `json:"id"`
	CustomerID        int64              `json:"customer_id"`
	RestaurantID      int64              `json:"restaurant_id"`
	AddressID         pgtype.Int8        `json:"address_id"`
	Status            OrderStatus        `json:"status"`
	SubtotalAmount    int64              `json:"subtotal_amount"`
	DeliveryFeeAmount int64              `json:"delivery_fee_amount"`
	TotalAmount       int64              `json:"total_amount"`
	Note              pgtype.Text        `json:"note"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type OrderItem struct {
	ID          int64              `json:"id"`
	OrderID     int64              `json:"order_id"`
	MenuItemID  int64              `json:"menu_item_id"`
	Name        string             `json:"name"`
	PriceAmount int64              `json:"price_amount"`
	Quantity    int32              `json:"quantity"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type OrderItemOption struct {
	ID              int64              `json:"id"`
	OrderItemID     int64              `json:"order_item_id"`
	OptionID        pgtype.Int8        `json:"option_id"`
	OptionValueID   pgtype.Int8        `json:"option_value_id"`
	OptionName      string             `json:"option_name"`
	OptionValueName string             `json:"option_value_name"`
	PriceAmount     int64              `json:"price_amount"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type OrderStatusEvent struct {
	ID          int64              `json:"id"`
	OrderID     int64              `json:"order_id"`
	FromStatus  NullOrderStatus    `json:"from_status"`
	ToStatus    OrderStatus        `json:"to_status"`
	ChangedByID pgtype.Int8        `json:"changed_by_id"`
	Reason      pgtype.Text        `json:"reason"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type PageSchema struct {
	ID             int64              `json:"id"`
	Key            string             `json:"key"`
	CurrentVersion int32              `json:"current_version"`
	SchemaData     []byte             `json:"schema_data"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type PageSchemaVersion struct {
	ID           int64              `json:"id"`
	PageSchemaID int64              `json:"page_schema_id"`
	Version      int32              `json:"version"`
	SchemaData   []byte             `json:"schema_data"`
	Note         pgtype.Text        `json:"note"`
	CreatorID    int64              `json:"creator_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Payment struct {
	ID                int64              `json:"id"`
	OrderID           int64              `json:"order_id"`
	UserID            int64              `json:"user_id"`
	Provider          PaymentProvider    `json:"provider"`
	ProviderPaymentID pgtype.Text        `json:"provider_payment_id"`
	Status            PaymentStatus      `json:"status"`
	Amount            int64              `json:"amount"`
	Currency          string             `json:"currency"`
	FailureReason     pgtype.Text        `json:"failure_reason"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	MetaData          []byte             `json:"meta_data"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type PaymentRefund struct {
	ID               int64              `json:"id"`
	PaymentID        int64              `json:"payment_id"`
	ProviderRefundID pgtype.Text        `json:"provider_refund_id"`
	Status           RefundStatus       `json:"status"`
	Amount           int64              `json:"amount"`
	Reason           pgtype.Text        `json:"reason"`
	RefundedAt       pgtype.Timestamptz `json:"refunded_at"`
	MetaData         []byte             `json:"meta_data"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type Permission struct {
	ID          int64              `json:"id"`
	Code        string             `json:"code"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Promotion struct {
	ID                int64              `json:"id"`
	Code              string             `json:"code"`
	Name              string             `json:"name"`
	Description       pgtype.Text        `json:"description"`
	Type              PromotionType      `json:"type"`
	Status            PromotionStatus    `json:"status"`
	PercentOff        pgtype.Int2        `json:"percent_off"`
	AmountOff         pgtype.Int8        `json:"amount_off"`
	MinOrderAmount    int64              `json:"min_order_amount"`
	MaxDiscountAmount pgtype.Int8        `json:"max_discount_amount"`
	UsageLimit        pgtype.Int4        `json:"usage_limit"`
	PerUserLimit      pgtype.Int4        `json:"per_user_limit"`
	RedemptionCount   int32              `json:"redemption_count"`
	StartsAt          pgtype.Timestamptz `json:"starts_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
	RestaurantID      pgtype.Int8        `json:"restaurant_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type PromotionRedemption struct {
	ID             int64              `json:"id"`
	PromotionID    int64              `json:"promotion_id"`
	UserID         int64              `json:"user_id"`
	OrderID        int64              `json:"order_id"`
	DiscountAmount int64              `json:"discount_amount"`
	RedeemedAt     pgtype.Timestamptz `json:"redeemed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type Restaurant struct {
	ID           int64              `json:"id"`
	OwnerID      int64              `json:"owner_id"`
	Name         string             `json:"name"`
	Description  pgtype.Text        `json:"description"`
	ImageUrl     pgtype.Text        `json:"image_url"`
	AddressLine1 string             `json:"address_line_1"`
	City         string             `json:"city"`
	Postcode     string             `json:"postcode"`
	Lat          pgtype.Numeric     `json:"lat"`
	Lng          pgtype.Numeric     `json:"lng"`
	Phone        pgtype.Text        `json:"phone"`
	IsOpen       bool               `json:"is_open"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type RestaurantOperatingHour struct {
	ID           int64              `json:"id"`
	RestaurantID int64              `json:"restaurant_id"`
	DayOfWeek    int16              `json:"day_of_week"`
	OpenTime     pgtype.Time        `json:"open_time"`
	CloseTime    pgtype.Time        `json:"close_time"`
	IsClosed     bool               `json:"is_closed"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type RestaurantPayout struct {
	ID                int64              `json:"id"`
	RestaurantID      int64              `json:"restaurant_id"`
	PeriodStartDate   pgtype.Date        `json:"period_start_date"`
	PeriodEndDate     pgtype.Date        `json:"period_end_date"`
	GrossAmount       int64              `json:"gross_amount"`
	PlatformFeeAmount int64              `json:"platform_fee_amount"`
	AdjustmentAmount  int64              `json:"adjustment_amount"`
	NetAmount         int64              `json:"net_amount"`
	Currency          string             `json:"currency"`
	Status            PayoutStatus       `json:"status"`
	PaidAt            pgtype.Timestamptz `json:"paid_at"`
	Reference         pgtype.Text        `json:"reference"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type Review struct {
	ID         int64              `json:"id"`
	OrderID    int64              `json:"order_id"`
	AuthorID   int64              `json:"author_id"`
	TargetType ReviewTargetType   `json:"target_type"`
	TargetID   int64              `json:"target_id"`
	Rating     int16              `json:"rating"`
	Comment    pgtype.Text        `json:"comment"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type RiderProfile struct {
	ID                  int64              `json:"id"`
	UserID              int64              `json:"user_id"`
	VehicleType         RiderVehicleType   `json:"vehicle_type"`
	VehiclePlate        pgtype.Text        `json:"vehicle_plate"`
	LicenseNumber       pgtype.Text        `json:"license_number"`
	LicenseExpiresAt    pgtype.Timestamptz `json:"license_expires_at"`
	IsVerified          bool               `json:"is_verified"`
	OnlineStatus        RiderOnlineStatus  `json:"online_status"`
	CurrentLat          pgtype.Numeric     `json:"current_lat"`
	CurrentLng          pgtype.Numeric     `json:"current_lng"`
	LocationUpdatedAt   pgtype.Timestamptz `json:"location_updated_at"`
	RatingAverage       pgtype.Numeric     `json:"rating_average"`
	RatingCount         int32              `json:"rating_count"`
	CompletedDeliveries int32              `json:"completed_deliveries"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type Role struct {
	ID        int64              `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	Persona   UserRole           `json:"persona"`
	IsSystem  bool               `json:"is_system"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type RolePermission struct {
	RoleID       int64              `json:"role_id"`
	PermissionID int64              `json:"permission_id"`
	GrantedAt    pgtype.Timestamptz `json:"granted_at"`
}

type Session struct {
	ID               int64              `json:"id"`
	UserID           int64              `json:"user_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	IpAddress        *netip.Addr        `json:"ip_address"`
	DeviceID         pgtype.Text        `json:"device_id"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	LastUsedAt       pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Email     string             `json:"email"`
	Phone     pgtype.Text        `json:"phone"`
	Role      UserRole           `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type UserPermissionGrant struct {
	UserID       int64              `json:"user_id"`
	PermissionID int64              `json:"permission_id"`
	Effect       int16              `json:"effect"`
	Scope        []byte             `json:"scope"`
	Reason       pgtype.Text        `json:"reason"`
	GrantedBy    pgtype.Int8        `json:"granted_by"`
	GrantedAt    pgtype.Timestamptz `json:"granted_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
}

type UserRoleAssignment struct {
	UserID    int64              `json:"user_id"`
	RoleID    int64              `json:"role_id"`
	GrantedBy pgtype.Int8        `json:"granted_by"`
	GrantedAt pgtype.Timestamptz `json:"granted_at"`
	Scope     []byte             `json:"scope"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type WebhookEvent struct {
	ID              int64              `json:"id"`
	Provider        string             `json:"provider"`
	EventType       string             `json:"event_type"`
	ProviderEventID string             `json:"provider_event_id"`
	Status          WebhookEventStatus `json:"status"`
	PayloadData     []byte             `json:"payload_data"`
	Signature       pgtype.Text        `json:"signature"`
	ErrorMessage    pgtype.Text        `json:"error_message"`
	RetryCount      int32              `json:"retry_count"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
	ReceivedAt      pgtype.Timestamptz `json:"received_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}
