// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package db

import (
	"context"
)

const countOrdersByRestaurants = `-- name: CountOrdersByRestaurants :one
SELECT COUNT(*) FROM orders
WHERE restaurant_id = ANY($1::bigint[])
  AND deleted_at IS NULL
`

func (q *Queries) CountOrdersByRestaurants(ctx context.Context, restaurantIds []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countOrdersByRestaurants, restaurantIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getOrderInRestaurants = `-- name: GetOrderInRestaurants :one
SELECT id, customer_id, restaurant_id, address_id, status, subtotal_amount, delivery_fee_amount, total_amount, note, created_at, updated_at, deleted_at FROM orders
WHERE id = $1::bigint
  AND restaurant_id = ANY($2::bigint[])
  AND deleted_at IS NULL
`

type GetOrderInRestaurantsParams struct {
	ID            int64
	RestaurantIds []int64
}

func (q *Queries) GetOrderInRestaurants(ctx context.Context, arg GetOrderInRestaurantsParams) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderInRestaurants, arg.ID, arg.RestaurantIds)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RestaurantID,
		&i.AddressID,
		&i.Status,
		&i.SubtotalAmount,
		&i.DeliveryFeeAmount,
		&i.TotalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listOrdersByRestaurants = `-- name: ListOrdersByRestaurants :many
SELECT id, customer_id, restaurant_id, address_id, status, subtotal_amount, delivery_fee_amount, total_amount, note, created_at, updated_at, deleted_at FROM orders
WHERE restaurant_id = ANY($1::bigint[])
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListOrdersByRestaurantsParams struct {
	RestaurantIds []int64
	PgOffset      int32
	PgLimit       int32
}

func (q *Queries) ListOrdersByRestaurants(ctx context.Context, arg ListOrdersByRestaurantsParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByRestaurants, arg.RestaurantIds, arg.PgOffset, arg.PgLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.RestaurantID,
			&i.AddressID,
			&i.Status,
			&i.SubtotalAmount,
			&i.DeliveryFeeAmount,
			&i.TotalAmount,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatusInRestaurants = `-- name: UpdateOrderStatusInRestaurants :one
UPDATE orders
SET status = $1::order_status, updated_at = NOW()
WHERE id = $2::bigint
  AND restaurant_id = ANY($3::bigint[])
  AND deleted_at IS NULL
RETURNING id, customer_id, restaurant_id, address_id, status, subtotal_amount, delivery_fee_amount, total_amount, note, created_at, updated_at, deleted_at
`

type UpdateOrderStatusInRestaurantsParams struct {
	Status        OrderStatus
	ID            int64
	RestaurantIds []int64
}

func (q *Queries) UpdateOrderStatusInRestaurants(ctx context.Context, arg UpdateOrderStatusInRestaurantsParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatusInRestaurants, arg.Status, arg.ID, arg.RestaurantIds)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.RestaurantID,
		&i.AddressID,
		&i.Status,
		&i.SubtotalAmount,
		&i.DeliveryFeeAmount,
		&i.TotalAmount,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
