// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_schemas.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPageSchema = `-- name: CreatePageSchema :one
INSERT INTO page_schemas (key, current_version, schema_data)
VALUES ($1, $2, $3)
RETURNING id, key, current_version, schema_data, created_at, updated_at, deleted_at
`

type CreatePageSchemaParams struct {
	Key            string
	CurrentVersion int32
	SchemaData     []byte
}

func (q *Queries) CreatePageSchema(ctx context.Context, arg CreatePageSchemaParams) (PageSchema, error) {
	row := q.db.QueryRow(ctx, createPageSchema, arg.Key, arg.CurrentVersion, arg.SchemaData)
	var i PageSchema
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CurrentVersion,
		&i.SchemaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPageSchemaByKey = `-- name: GetPageSchemaByKey :one
SELECT id, key, current_version, schema_data, created_at, updated_at, deleted_at FROM page_schemas
WHERE key = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPageSchemaByKey(ctx context.Context, key string) (PageSchema, error) {
	row := q.db.QueryRow(ctx, getPageSchemaByKey, key)
	var i PageSchema
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CurrentVersion,
		&i.SchemaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPageSchemas = `-- name: ListPageSchemas :many
SELECT id, key, current_version, schema_data, created_at, updated_at, deleted_at FROM page_schemas
WHERE deleted_at IS NULL
ORDER BY key ASC
`

func (q *Queries) ListPageSchemas(ctx context.Context) ([]PageSchema, error) {
	rows, err := q.db.Query(ctx, listPageSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageSchema
	for rows.Next() {
		var i PageSchema
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.CurrentVersion,
			&i.SchemaData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPageSchemasWithUpdater = `-- name: ListPageSchemasWithUpdater :many
SELECT
  ps.id,
  ps.key,
  ps.current_version,
  ps.schema_data,
  ps.created_at,
  ps.updated_at,
  ps.deleted_at,
  u.id    AS updater_id,
  u.name  AS updater_name,
  u.email AS updater_email
FROM page_schemas ps
LEFT JOIN page_schema_versions psv
  ON psv.page_schema_id = ps.id
  AND psv.version = ps.current_version
  AND psv.deleted_at IS NULL
LEFT JOIN users u
  ON u.id = psv.creator_id
WHERE ps.deleted_at IS NULL
ORDER BY ps.key ASC
`

type ListPageSchemasWithUpdaterRow struct {
	ID             int64
	Key            string
	CurrentVersion int32
	SchemaData     []byte
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
	UpdaterID      pgtype.Int8
	UpdaterName    pgtype.Text
	UpdaterEmail   pgtype.Text
}

func (q *Queries) ListPageSchemasWithUpdater(ctx context.Context) ([]ListPageSchemasWithUpdaterRow, error) {
	rows, err := q.db.Query(ctx, listPageSchemasWithUpdater)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPageSchemasWithUpdaterRow
	for rows.Next() {
		var i ListPageSchemasWithUpdaterRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.CurrentVersion,
			&i.SchemaData,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.UpdaterID,
			&i.UpdaterName,
			&i.UpdaterEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePageSchemaByKey = `-- name: SoftDeletePageSchemaByKey :one
UPDATE page_schemas
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE key = $1 AND deleted_at IS NULL
RETURNING id, key, current_version, schema_data, created_at, updated_at, deleted_at
`

func (q *Queries) SoftDeletePageSchemaByKey(ctx context.Context, key string) (PageSchema, error) {
	row := q.db.QueryRow(ctx, softDeletePageSchemaByKey, key)
	var i PageSchema
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CurrentVersion,
		&i.SchemaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePageSchemaCurrent = `-- name: UpdatePageSchemaCurrent :one
UPDATE page_schemas
SET current_version = $2,
    schema_data = $3,
    updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, key, current_version, schema_data, created_at, updated_at, deleted_at
`

type UpdatePageSchemaCurrentParams struct {
	ID             int64
	CurrentVersion int32
	SchemaData     []byte
}

func (q *Queries) UpdatePageSchemaCurrent(ctx context.Context, arg UpdatePageSchemaCurrentParams) (PageSchema, error) {
	row := q.db.QueryRow(ctx, updatePageSchemaCurrent, arg.ID, arg.CurrentVersion, arg.SchemaData)
	var i PageSchema
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.CurrentVersion,
		&i.SchemaData,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
