// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: page_schema_versions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPageSchemaVersion = `-- name: CreatePageSchemaVersion :one
INSERT INTO page_schema_versions (page_schema_id, version, schema_data, note, creator_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, page_schema_id, version, schema_data, note, creator_id, created_at, updated_at, deleted_at
`

type CreatePageSchemaVersionParams struct {
	PageSchemaID int64
	Version      int32
	SchemaData   []byte
	Note         pgtype.Text
	CreatorID    int64
}

func (q *Queries) CreatePageSchemaVersion(ctx context.Context, arg CreatePageSchemaVersionParams) (PageSchemaVersion, error) {
	row := q.db.QueryRow(ctx, createPageSchemaVersion,
		arg.PageSchemaID,
		arg.Version,
		arg.SchemaData,
		arg.Note,
		arg.CreatorID,
	)
	var i PageSchemaVersion
	err := row.Scan(
		&i.ID,
		&i.PageSchemaID,
		&i.Version,
		&i.SchemaData,
		&i.Note,
		&i.CreatorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPageSchemaVersion = `-- name: GetPageSchemaVersion :one
SELECT id, page_schema_id, version, schema_data, note, creator_id, created_at, updated_at, deleted_at FROM page_schema_versions
WHERE page_schema_id = $1 AND version = $2 AND deleted_at IS NULL
LIMIT 1
`

type GetPageSchemaVersionParams struct {
	PageSchemaID int64
	Version      int32
}

func (q *Queries) GetPageSchemaVersion(ctx context.Context, arg GetPageSchemaVersionParams) (PageSchemaVersion, error) {
	row := q.db.QueryRow(ctx, getPageSchemaVersion, arg.PageSchemaID, arg.Version)
	var i PageSchemaVersion
	err := row.Scan(
		&i.ID,
		&i.PageSchemaID,
		&i.Version,
		&i.SchemaData,
		&i.Note,
		&i.CreatorID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPageSchemaVersionsBySchemaID = `-- name: ListPageSchemaVersionsBySchemaID :many
SELECT id, page_schema_id, version, schema_data, note, creator_id, created_at, updated_at, deleted_at FROM page_schema_versions
WHERE page_schema_id = $1 AND deleted_at IS NULL
ORDER BY version DESC
`

func (q *Queries) ListPageSchemaVersionsBySchemaID(ctx context.Context, pageSchemaID int64) ([]PageSchemaVersion, error) {
	rows, err := q.db.Query(ctx, listPageSchemaVersionsBySchemaID, pageSchemaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PageSchemaVersion
	for rows.Next() {
		var i PageSchemaVersion
		if err := rows.Scan(
			&i.ID,
			&i.PageSchemaID,
			&i.Version,
			&i.SchemaData,
			&i.Note,
			&i.CreatorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
