// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package db

import (
	"context"
)

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, code, description, created_at, updated_at, deleted_at FROM permissions
WHERE code = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code string) (Permission, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i Permission
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, code, description, created_at, updated_at, deleted_at FROM permissions
WHERE deleted_at IS NULL
ORDER BY code
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
