// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error)
	AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]User, error)
	AdminUpdateUserRole(ctx context.Context, arg AdminUpdateUserRoleParams) (User, error)
	CreatePageSchema(ctx context.Context, arg CreatePageSchemaParams) (PageSchema, error)
	CreatePageSchemaVersion(ctx context.Context, arg CreatePageSchemaVersionParams) (PageSchemaVersion, error)
	CreatePasswordCredential(ctx context.Context, arg CreatePasswordCredentialParams) (AuthCredential, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetActiveSessionByTokenHash(ctx context.Context, refreshTokenHash string) (Session, error)
	GetPageSchemaByKey(ctx context.Context, key string) (PageSchema, error)
	GetPageSchemaVersion(ctx context.Context, arg GetPageSchemaVersionParams) (PageSchemaVersion, error)
	GetPasswordCredentialByUserID(ctx context.Context, userID int64) (AuthCredential, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListPageSchemaVersionsBySchemaID(ctx context.Context, pageSchemaID int64) ([]PageSchemaVersion, error)
	ListPageSchemas(ctx context.Context) ([]PageSchema, error)
	ListPageSchemasWithUpdater(ctx context.Context) ([]ListPageSchemasWithUpdaterRow, error)
	RevokeSession(ctx context.Context, id int64) error
	SoftDeletePageSchemaByKey(ctx context.Context, key string) (PageSchema, error)
	UpdateAuthCredentialLastLogin(ctx context.Context, id int64) error
	UpdatePageSchemaCurrent(ctx context.Context, arg UpdatePageSchemaCurrentParams) (PageSchema, error)
	UpdateSessionLastUsed(ctx context.Context, id int64) error
}

var _ Querier = (*Queries)(nil)
