// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: restaurants.sql

package db

import (
	"context"
)

const getRestaurantByID = `-- name: GetRestaurantByID :one
SELECT id, owner_id, name, description, image_url, address_line_1, city, postcode, lat, lng, phone, is_open, created_at, updated_at, deleted_at FROM restaurants
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRestaurantByID(ctx context.Context, id int64) (Restaurant, error) {
	row := q.db.QueryRow(ctx, getRestaurantByID, id)
	var i Restaurant
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.ImageUrl,
		&i.AddressLine1,
		&i.City,
		&i.Postcode,
		&i.Lat,
		&i.Lng,
		&i.Phone,
		&i.IsOpen,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRestaurantIDsByOwner = `-- name: ListRestaurantIDsByOwner :many
SELECT id FROM restaurants
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY id
`

func (q *Queries) ListRestaurantIDsByOwner(ctx context.Context, ownerID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listRestaurantIDsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestaurantSummariesByIDs = `-- name: ListRestaurantSummariesByIDs :many
SELECT id, name FROM restaurants
WHERE id = ANY($1::bigint[]) AND deleted_at IS NULL
ORDER BY id
`

type ListRestaurantSummariesByIDsRow struct {
	ID   int64
	Name string
}

func (q *Queries) ListRestaurantSummariesByIDs(ctx context.Context, dollar_1 []int64) ([]ListRestaurantSummariesByIDsRow, error) {
	rows, err := q.db.Query(ctx, listRestaurantSummariesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRestaurantSummariesByIDsRow
	for rows.Next() {
		var i ListRestaurantSummariesByIDsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRestaurantsByOwner = `-- name: ListRestaurantsByOwner :many
SELECT id, owner_id, name, description, image_url, address_line_1, city, postcode, lat, lng, phone, is_open, created_at, updated_at, deleted_at FROM restaurants
WHERE owner_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListRestaurantsByOwner(ctx context.Context, ownerID int64) ([]Restaurant, error) {
	rows, err := q.db.Query(ctx, listRestaurantsByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Restaurant
	for rows.Next() {
		var i Restaurant
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Description,
			&i.ImageUrl,
			&i.AddressLine1,
			&i.City,
			&i.Postcode,
			&i.Lat,
			&i.Lng,
			&i.Phone,
			&i.IsOpen,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
