// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRolePermissionByCode = `-- name: AddRolePermissionByCode :exec
INSERT INTO role_permissions (role_id, permission_id)
SELECT $1::bigint, p.id
FROM permissions p
WHERE p.code = $2
  AND p.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type AddRolePermissionByCodeParams struct {
	Column1 int64  `json:"column_1"`
	Code    string `json:"code"`
}

// Inserts a (role_id, permission_id) row by looking up the permission code.
// No-op when the permission code does not exist.
func (q *Queries) AddRolePermissionByCode(ctx context.Context, arg AddRolePermissionByCodeParams) error {
	_, err := q.db.Exec(ctx, addRolePermissionByCode, arg.Column1, arg.Code)
	return err
}

const countUserAssignmentsByRoleID = `-- name: CountUserAssignmentsByRoleID :one
SELECT COUNT(*) FROM user_role_assignments WHERE role_id = $1
`

func (q *Queries) CountUserAssignmentsByRoleID(ctx context.Context, roleID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUserAssignmentsByRoleID, roleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (code, name, persona, is_system)
VALUES ($1, $2, $3, FALSE)
RETURNING id, code, name, persona, is_system, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	Code    string   `json:"code"`
	Name    string   `json:"name"`
	Persona UserRole `json:"persona"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole, arg.Code, arg.Name, arg.Persona)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Persona,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRolePermissions = `-- name: DeleteRolePermissions :exec
DELETE FROM role_permissions WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissions(ctx context.Context, roleID int64) error {
	_, err := q.db.Exec(ctx, deleteRolePermissions, roleID)
	return err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name, persona, is_system, created_at, updated_at, deleted_at FROM roles
WHERE code = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Persona,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, code, name, persona, is_system, created_at, updated_at, deleted_at FROM roles
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetRoleByID(ctx context.Context, id int64) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Persona,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPermissionsByRoleID = `-- name: ListPermissionsByRoleID :many
SELECT p.id, p.code, p.description, p.created_at, p.updated_at, p.deleted_at
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
WHERE rp.role_id = $1
  AND p.deleted_at IS NULL
ORDER BY p.code
`

func (q *Queries) ListPermissionsByRoleID(ctx context.Context, roleID int64) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissionsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, code, name, persona, is_system, created_at, updated_at, deleted_at FROM roles
WHERE deleted_at IS NULL
ORDER BY persona, code
`

func (q *Queries) ListRoles(ctx context.Context) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Persona,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByPersona = `-- name: ListRolesByPersona :many
SELECT id, code, name, persona, is_system, created_at, updated_at, deleted_at FROM roles
WHERE deleted_at IS NULL
  AND persona = $1
ORDER BY code
`

func (q *Queries) ListRolesByPersona(ctx context.Context, persona UserRole) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByPersona, persona)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Persona,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithPermissions = `-- name: ListRolesWithPermissions :many
SELECT
  r.id         AS role_id,
  r.code       AS role_code,
  r.name       AS role_name,
  r.persona    AS role_persona,
  r.is_system  AS role_is_system,
  p.code       AS permission_code
FROM roles r
LEFT JOIN role_permissions rp ON rp.role_id = r.id
LEFT JOIN permissions p ON p.id = rp.permission_id AND p.deleted_at IS NULL
WHERE r.deleted_at IS NULL
ORDER BY r.persona, r.code, p.code
`

type ListRolesWithPermissionsRow struct {
	RoleID         int64       `json:"role_id"`
	RoleCode       string      `json:"role_code"`
	RoleName       string      `json:"role_name"`
	RolePersona    UserRole    `json:"role_persona"`
	RoleIsSystem   bool        `json:"role_is_system"`
	PermissionCode pgtype.Text `json:"permission_code"`
}

func (q *Queries) ListRolesWithPermissions(ctx context.Context) ([]ListRolesWithPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listRolesWithPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesWithPermissionsRow
	for rows.Next() {
		var i ListRolesWithPermissionsRow
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleCode,
			&i.RoleName,
			&i.RolePersona,
			&i.RoleIsSystem,
			&i.PermissionCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :exec
UPDATE roles
SET deleted_at = NOW(),
    updated_at = NOW()
WHERE id = $1
  AND is_system = FALSE
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRole(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, softDeleteRole, id)
	return err
}

const updateRoleName = `-- name: UpdateRoleName :one
UPDATE roles
SET name       = $2,
    updated_at = NOW()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, code, name, persona, is_system, created_at, updated_at, deleted_at
`

type UpdateRoleNameParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateRoleName(ctx context.Context, arg UpdateRoleNameParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRoleName, arg.ID, arg.Name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Persona,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
