// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_permission_grants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserGrant = `-- name: DeleteUserGrant :exec
DELETE FROM user_permission_grants
WHERE user_id = $1 AND permission_id = $2
`

type DeleteUserGrantParams struct {
	UserID       int64
	PermissionID int64
}

func (q *Queries) DeleteUserGrant(ctx context.Context, arg DeleteUserGrantParams) error {
	_, err := q.db.Exec(ctx, deleteUserGrant, arg.UserID, arg.PermissionID)
	return err
}

const getUserGrant = `-- name: GetUserGrant :one
SELECT
  upg.user_id,
  upg.permission_id,
  p.code        AS permission_code,
  upg.effect,
  upg.scope,
  upg.reason,
  upg.granted_by,
  upg.granted_at,
  upg.expires_at
FROM user_permission_grants upg
JOIN permissions p ON p.id = upg.permission_id
WHERE upg.user_id = $1 AND upg.permission_id = $2
LIMIT 1
`

type GetUserGrantParams struct {
	UserID       int64
	PermissionID int64
}

type GetUserGrantRow struct {
	UserID         int64
	PermissionID   int64
	PermissionCode string
	Effect         int16
	Scope          []byte
	Reason         pgtype.Text
	GrantedBy      pgtype.Int8
	GrantedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

func (q *Queries) GetUserGrant(ctx context.Context, arg GetUserGrantParams) (GetUserGrantRow, error) {
	row := q.db.QueryRow(ctx, getUserGrant, arg.UserID, arg.PermissionID)
	var i GetUserGrantRow
	err := row.Scan(
		&i.UserID,
		&i.PermissionID,
		&i.PermissionCode,
		&i.Effect,
		&i.Scope,
		&i.Reason,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const listUserGrants = `-- name: ListUserGrants :many
SELECT
  upg.user_id,
  upg.permission_id,
  p.code        AS permission_code,
  upg.effect,
  upg.scope,
  upg.reason,
  upg.granted_by,
  upg.granted_at,
  upg.expires_at
FROM user_permission_grants upg
JOIN permissions p ON p.id = upg.permission_id
WHERE upg.user_id = $1
  AND p.deleted_at IS NULL
ORDER BY p.code
`

type ListUserGrantsRow struct {
	UserID         int64
	PermissionID   int64
	PermissionCode string
	Effect         int16
	Scope          []byte
	Reason         pgtype.Text
	GrantedBy      pgtype.Int8
	GrantedAt      pgtype.Timestamptz
	ExpiresAt      pgtype.Timestamptz
}

// Returns raw grant rows for a user (admin UI: show all including expired).
func (q *Queries) ListUserGrants(ctx context.Context, userID int64) ([]ListUserGrantsRow, error) {
	rows, err := q.db.Query(ctx, listUserGrants, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGrantsRow
	for rows.Next() {
		var i ListUserGrantsRow
		if err := rows.Scan(
			&i.UserID,
			&i.PermissionID,
			&i.PermissionCode,
			&i.Effect,
			&i.Scope,
			&i.Reason,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserGrantsForEval = `-- name: ListUserGrantsForEval :many
SELECT
  p.code    AS permission_code,
  upg.effect,
  upg.scope,
  upg.expires_at
FROM user_permission_grants upg
JOIN permissions p ON p.id = upg.permission_id
WHERE upg.user_id = $1
  AND p.deleted_at IS NULL
  AND (upg.expires_at IS NULL OR upg.expires_at > NOW())
ORDER BY p.code
`

type ListUserGrantsForEvalRow struct {
	PermissionCode string
	Effect         int16
	Scope          []byte
	ExpiresAt      pgtype.Timestamptz
}

// Returns only non-expired grant rows for Actor evaluation.
func (q *Queries) ListUserGrantsForEval(ctx context.Context, userID int64) ([]ListUserGrantsForEvalRow, error) {
	rows, err := q.db.Query(ctx, listUserGrantsForEval, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserGrantsForEvalRow
	for rows.Next() {
		var i ListUserGrantsForEvalRow
		if err := rows.Scan(
			&i.PermissionCode,
			&i.Effect,
			&i.Scope,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserGrant = `-- name: UpsertUserGrant :exec
INSERT INTO user_permission_grants (
  user_id, permission_id, effect, scope, reason, granted_by, expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (user_id, permission_id) DO UPDATE
SET effect     = EXCLUDED.effect,
    scope      = EXCLUDED.scope,
    reason     = EXCLUDED.reason,
    granted_by = EXCLUDED.granted_by,
    expires_at = EXCLUDED.expires_at,
    granted_at = NOW()
`

type UpsertUserGrantParams struct {
	UserID       int64
	PermissionID int64
	Effect       int16
	Scope        []byte
	Reason       pgtype.Text
	GrantedBy    pgtype.Int8
	ExpiresAt    pgtype.Timestamptz
}

// Writes / updates a single (user_id, permission_id) grant.
func (q *Queries) UpsertUserGrant(ctx context.Context, arg UpsertUserGrantParams) error {
	_, err := q.db.Exec(ctx, upsertUserGrant,
		arg.UserID,
		arg.PermissionID,
		arg.Effect,
		arg.Scope,
		arg.Reason,
		arg.GrantedBy,
		arg.ExpiresAt,
	)
	return err
}
