// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adminCountUsers = `-- name: AdminCountUsers :one
SELECT COUNT(*) FROM users
WHERE deleted_at IS NULL
  AND ($1::user_role IS NULL OR role = $1)
  AND (
    $2::text IS NULL
    OR name  ILIKE '%' || $2 || '%'
    OR email ILIKE '%' || $2 || '%'
  )
`

type AdminCountUsersParams struct {
	Role    NullUserRole `json:"role"`
	Keyword pgtype.Text  `json:"keyword"`
}

func (q *Queries) AdminCountUsers(ctx context.Context, arg AdminCountUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCountUsers, arg.Role, arg.Keyword)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const adminListUsers = `-- name: AdminListUsers :many
SELECT id, name, email, phone, role, created_at, updated_at, deleted_at FROM users
WHERE deleted_at IS NULL
  AND ($3::user_role IS NULL OR role = $3)
  AND (
    $4::text IS NULL
    OR name  ILIKE '%' || $4 || '%'
    OR email ILIKE '%' || $4 || '%'
  )
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type AdminListUsersParams struct {
	Limit   int32        `json:"limit"`
	Offset  int32        `json:"offset"`
	Role    NullUserRole `json:"role"`
	Keyword pgtype.Text  `json:"keyword"`
}

func (q *Queries) AdminListUsers(ctx context.Context, arg AdminListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, adminListUsers,
		arg.Limit,
		arg.Offset,
		arg.Role,
		arg.Keyword,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.Role,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminUpdateUserRole = `-- name: AdminUpdateUserRole :one
UPDATE users
SET role = $2, updated_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, email, phone, role, created_at, updated_at, deleted_at
`

type AdminUpdateUserRoleParams struct {
	ID   int64    `json:"id"`
	Role UserRole `json:"role"`
}

func (q *Queries) AdminUpdateUserRole(ctx context.Context, arg AdminUpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, adminUpdateUserRole, arg.ID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, phone, role)
VALUES ($1, $2, $3, $4)
RETURNING id, name, email, phone, role, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	Name  string      `json:"name"`
	Email string      `json:"email"`
	Phone pgtype.Text `json:"phone"`
	Role  UserRole    `json:"role"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.Role,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone, role, created_at, updated_at, deleted_at FROM users
WHERE email = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone, role, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
