// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_roles.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRole = `-- name: AddUserRole :exec
INSERT INTO user_role_assignments (user_id, role_id, granted_by)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddUserRoleParams struct {
	UserID    int64       `json:"user_id"`
	RoleID    int64       `json:"role_id"`
	GrantedBy pgtype.Int8 `json:"granted_by"`
}

func (q *Queries) AddUserRole(ctx context.Context, arg AddUserRoleParams) error {
	_, err := q.db.Exec(ctx, addUserRole, arg.UserID, arg.RoleID, arg.GrantedBy)
	return err
}

const deleteUserRolesByUserID = `-- name: DeleteUserRolesByUserID :exec
DELETE FROM user_role_assignments WHERE user_id = $1
`

func (q *Queries) DeleteUserRolesByUserID(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, deleteUserRolesByUserID, userID)
	return err
}

const grantDefaultRoleForPersona = `-- name: GrantDefaultRoleForPersona :exec
INSERT INTO user_role_assignments (user_id, role_id, granted_by)
SELECT $1::bigint, r.id, $2::bigint
FROM roles r
WHERE r.code = ($3::text || '.default')
  AND r.deleted_at IS NULL
ON CONFLICT DO NOTHING
`

type GrantDefaultRoleForPersonaParams struct {
	UserID    int64       `json:"user_id"`
	GrantedBy pgtype.Int8 `json:"granted_by"`
	Persona   string      `json:"persona"`
}

// Grants the <persona>.default role to the user (no-op if already granted).
func (q *Queries) GrantDefaultRoleForPersona(ctx context.Context, arg GrantDefaultRoleForPersonaParams) error {
	_, err := q.db.Exec(ctx, grantDefaultRoleForPersona, arg.UserID, arg.GrantedBy, arg.Persona)
	return err
}

const listRolePermissionCodesByRoleIDs = `-- name: ListRolePermissionCodesByRoleIDs :many
SELECT rp.role_id, p.code
FROM role_permissions rp
JOIN permissions p ON p.id = rp.permission_id
WHERE rp.role_id = ANY($1::bigint[])
  AND p.deleted_at IS NULL
ORDER BY rp.role_id, p.code
`

type ListRolePermissionCodesByRoleIDsRow struct {
	RoleID int64  `json:"role_id"`
	Code   string `json:"code"`
}

// Returns (role_id, permission_code) pairs for a batch of role ids.
// Used by LoadActor to hydrate each RoleBinding's permission set in one round-trip.
func (q *Queries) ListRolePermissionCodesByRoleIDs(ctx context.Context, dollar_1 []int64) ([]ListRolePermissionCodesByRoleIDsRow, error) {
	rows, err := q.db.Query(ctx, listRolePermissionCodesByRoleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolePermissionCodesByRoleIDsRow
	for rows.Next() {
		var i ListRolePermissionCodesByRoleIDsRow
		if err := rows.Scan(&i.RoleID, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserPermissionCodes = `-- name: ListUserPermissionCodes :many
SELECT DISTINCT p.code
FROM permissions p
JOIN role_permissions rp ON rp.permission_id = p.id
JOIN roles r ON r.id = rp.role_id
JOIN user_role_assignments ura ON ura.role_id = r.id
JOIN users u ON u.id = ura.user_id
WHERE ura.user_id = $1
  AND p.deleted_at IS NULL
  AND r.deleted_at IS NULL
  AND u.deleted_at IS NULL
  AND r.persona = u.role
ORDER BY p.code
`

// Returns distinct permission codes derived from the user's roles, persona-filtered.
func (q *Queries) ListUserPermissionCodes(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserPermissionCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleBindings = `-- name: ListUserRoleBindings :many
SELECT
  r.id         AS role_id,
  r.code       AS role_code,
  r.persona    AS role_persona,
  ura.scope    AS scope,
  ura.expires_at AS expires_at
FROM user_role_assignments ura
JOIN roles r ON r.id = ura.role_id
JOIN users u ON u.id = ura.user_id
WHERE ura.user_id = $1
  AND r.deleted_at IS NULL
  AND u.deleted_at IS NULL
  AND r.persona = u.role
  AND (ura.expires_at IS NULL OR ura.expires_at > NOW())
ORDER BY r.code
`

type ListUserRoleBindingsRow struct {
	RoleID      int64              `json:"role_id"`
	RoleCode    string             `json:"role_code"`
	RolePersona UserRole           `json:"role_persona"`
	Scope       []byte             `json:"scope"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Returns the full role binding (role + scope + expires_at) for a user,
// persona-filtered. Used by LoadActor.
func (q *Queries) ListUserRoleBindings(ctx context.Context, userID int64) ([]ListUserRoleBindingsRow, error) {
	rows, err := q.db.Query(ctx, listUserRoleBindings, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserRoleBindingsRow
	for rows.Next() {
		var i ListUserRoleBindingsRow
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleCode,
			&i.RolePersona,
			&i.Scope,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRoleCodes = `-- name: ListUserRoleCodes :many
SELECT r.code
FROM roles r
JOIN user_role_assignments ura ON ura.role_id = r.id
JOIN users u ON u.id = ura.user_id
WHERE ura.user_id = $1
  AND r.deleted_at IS NULL
  AND u.deleted_at IS NULL
  AND r.persona = u.role
ORDER BY r.code
`

// Returns role codes scoped to the user's current persona.
func (q *Queries) ListUserRoleCodes(ctx context.Context, userID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listUserRoleCodes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserRolesDetail = `-- name: ListUserRolesDetail :many
SELECT r.id, r.code, r.name, r.persona, r.is_system, r.created_at, r.updated_at, r.deleted_at
FROM roles r
JOIN user_role_assignments ura ON ura.role_id = r.id
JOIN users u ON u.id = ura.user_id
WHERE ura.user_id = $1
  AND r.deleted_at IS NULL
  AND u.deleted_at IS NULL
  AND r.persona = u.role
ORDER BY r.code
`

// Full role rows for a user (persona-filtered).
func (q *Queries) ListUserRolesDetail(ctx context.Context, userID int64) ([]Role, error) {
	rows, err := q.db.Query(ctx, listUserRolesDetail, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Persona,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUserRoleBinding = `-- name: UpsertUserRoleBinding :exec
INSERT INTO user_role_assignments (user_id, role_id, granted_by, scope, expires_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id, role_id) DO UPDATE
SET scope      = EXCLUDED.scope,
    expires_at = EXCLUDED.expires_at,
    granted_by = EXCLUDED.granted_by,
    granted_at = NOW()
`

type UpsertUserRoleBindingParams struct {
	UserID    int64              `json:"user_id"`
	RoleID    int64              `json:"role_id"`
	GrantedBy pgtype.Int8        `json:"granted_by"`
	Scope     []byte             `json:"scope"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Writes a (user_id, role_id) assignment with scope + expires_at.
// Re-runnable: on conflict overwrites scope / expires_at / granted_by.
func (q *Queries) UpsertUserRoleBinding(ctx context.Context, arg UpsertUserRoleBindingParams) error {
	_, err := q.db.Exec(ctx, upsertUserRoleBinding,
		arg.UserID,
		arg.RoleID,
		arg.GrantedBy,
		arg.Scope,
		arg.ExpiresAt,
	)
	return err
}
